namespace SWWerkplaats.Configurator.Portal
{
    public static class PortalLibraryHtml
    {
        public static string Page()
        {
            return @"<!doctype html>
<html lang=""nl""><head><meta charset=""utf-8""><meta name=""viewport"" content=""width=device-width,initial-scale=1""><title>Bibliotheekbeheer</title>
<style>
:root{--bg:#f5f5f7;--panel:#fff;--ink:#1d1d1f;--muted:#6e6e73;--line:#d8d8de;--accent:#0071e3;--danger:#b42318}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif}header{height:68px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 28px;position:sticky;top:0}main{max-width:1400px;margin:0 auto;padding:24px;display:grid;grid-template-columns:330px 1fr;gap:20px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:20px;padding:18px}h1{font-size:22px}h2{margin-top:0}.tabs,.actions{display:flex;gap:8px;flex-wrap:wrap}.tabs button.active{background:var(--accent);color:#fff}.list{display:grid;gap:7px;margin-top:14px;max-height:68vh;overflow:auto}.list button{text-align:left;background:#f1f3f6}.list button.active{outline:2px solid var(--accent)}button{border:0;border-radius:10px;padding:10px 12px;font-weight:700;cursor:pointer;background:#e9ecf1;color:var(--ink)}button.primary{background:var(--accent);color:#fff}button.danger{background:#fee4e2;color:var(--danger)}label{display:block;font-size:12px;color:var(--muted);font-weight:700;margin:10px 0 5px}input{width:100%;border:1px solid var(--line);border-radius:10px;padding:10px;background:#f8f9fb}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.wide{grid-column:span 2}.message{margin-top:12px;color:var(--muted)}@media(max-width:850px){main{grid-template-columns:1fr}.grid{grid-template-columns:1fr}.wide{grid-column:auto}}
</style></head><body>
<header><h1>Rail- en plankdragerbibliotheek</h1><div class=""actions""><button onclick=""location.href='/'"">Terug naar configurator</button><button class=""primary"" onclick=""saveAll()"">Alles opslaan</button></div></header>
<main><section class=""panel""><div class=""tabs""><button id=""railTab"" class=""active"" onclick=""setType('rail')"">Ladegeleiders</button><button id=""supportTab"" onclick=""setType('support')"">Plankdragers</button></div><div class=""actions"" style=""margin-top:12px""><button onclick=""addItem()"">Nieuw</button><button class=""danger"" onclick=""deleteItem()"">Verwijder</button></div><div id=""list"" class=""list""></div></section>
<section class=""panel""><h2 id=""editorTitle"">Ladegeleider</h2><div id=""editor"" class=""grid""></div><div id=""message"" class=""message"">Wijzigingen worden pas actief na Alles opslaan.</div></section></main>
<script>
let data={rails:[],shelfSupports:[]},type='rail',index=0;const fields={rail:[['Id','ID','text'],['Name','Naam','text'],['LengthMm','Lengte mm','number'],['ThicknessMm','Dikte mm','number'],['CabinetHolePositionsMm','Kastgatposities mm (; gescheiden)','text'],['CabinetOppositeHolePositionsMm','Tegenoverliggende kastgatposities','text'],['CabinetVerticalOffsetMm','Verticale offset kast mm','number'],['CabinetHoleDiameterMm','Kastgat Ø mm','number'],['DrawerHolePositionsMm','Ladegatposities mm (; gescheiden)','text'],['DrawerVerticalOffsetMm','Verticale offset lade mm','number'],['DrawerHoleDiameterMm','Ladegat Ø mm','number'],['DrawerFrontInsertionCompensationMm','Voorcompensatie mm','number'],['FastenerName','Bevestiger','text'],['CabinetFastenerDiameterMm','Bevestiger Ø mm','number'],['CabinetFastenerLengthMm','Bevestiger lengte mm','number'],['CabinetFastenerPassingStackMm','Doorvoerstack mm','number'],['CabinetFastenerHeadStyle','Kopvorm','text']],support:[['Id','ID','text'],['Name','Naam','text'],['ThicknessMm','Dikte mm','number'],['HeightMm','Hoogte mm','number'],['HoleDiameterMm','Gat Ø mm','number'],['HoleSpacingMm','Gatafstand mm','number'],['FrontInsetMm','Voorinspringing mm','number'],['BackInsetMm','Achterinspringing mm','number'],['FirstHoleHeightMm','Eerste gathoogte mm','number']]};
const arr=()=>type==='rail'?data.rails:data.shelfSupports;function setType(v){sync();type=v;index=0;document.getElementById('railTab').classList.toggle('active',v==='rail');document.getElementById('supportTab').classList.toggle('active',v==='support');render()}function render(){renderList();renderEditor()}function renderList(){const host=document.getElementById('list');host.innerHTML='';arr().forEach((item,i)=>{const b=document.createElement('button');b.textContent=(item.Id||'(zonder ID)')+' — '+(item.Name||'');b.classList.toggle('active',i===index);b.onclick=()=>{sync();index=i;render()};host.appendChild(b)})}function renderEditor(){const item=arr()[index];document.getElementById('editorTitle').textContent=type==='rail'?'Ladegeleider':'Plankdrager';const host=document.getElementById('editor');host.innerHTML='';if(!item){host.textContent='Maak eerst een item aan.';return}fields[type].forEach(([key,label,inputType])=>{const w=document.createElement('div');if(inputType==='text'&&key!=='Id')w.className='wide';const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.id='f_'+key;input.type=inputType;input.value=item[key]??'';if(inputType==='number')input.step='any';w.append(l,input);host.appendChild(w)})}function sync(){const item=arr()[index];if(!item)return;fields[type].forEach(([key,,inputType])=>{const input=document.getElementById('f_'+key);if(input)item[key]=inputType==='number'?(Number(input.value)||0):input.value.trim()})}function addItem(){sync();const item={Id:(type==='rail'?'rail_':'support_')+Date.now(),Name:'Nieuw item'};arr().push(item);index=arr().length-1;render()}function deleteItem(){if(!arr()[index]||!confirm('Dit item verwijderen?'))return;arr().splice(index,1);index=Math.max(0,index-1);render()}async function saveAll(){sync();const response=await fetch('/api/library',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok||result.ok===false)throw new Error(result.error||'Opslaan mislukt');data={rails:result.rails||[],shelfSupports:result.shelfSupports||[]};index=0;render();document.getElementById('message').textContent='Opgeslagen in '+result.path}fetch('/api/library').then(r=>r.json()).then(v=>{data={rails:v.rails||[],shelfSupports:v.shelfSupports||[]};render()}).catch(e=>document.getElementById('message').textContent=e.message);
</script></body></html>";
        }
    }
}
